# ***Fares Hesham Mohammed***
## ***Data Engineering***
### ***Python 3rd Task***

In [ ]:
pip install ydata-profiling

In [381]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from ydata_profiling import ProfileReport

In [382]:
df = pd.read_csv("/content/SuperMarket.csv")

## *Identify Data*

In [383]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.22,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.048,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,NaN,10:37:00 AM,E-wallet,604.17,4.761905,30.2085,5.3

<mark>**Sales = Quantity * Unit Price + Tax 5%**</mark>

<mark>**Cogs = Quantity * Unit Price**</mark>

<mark>**Gross Income = Tax 5%**</mark>

In [384]:
df.shape

(1014, 17)

In [385]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1014 non-null   object
 1   Branch                   1014 non-null   object
 2   City                     1014 non-null   object
 3      Customer type         1014 non-null   object
 4   Gender                   1014 non-null   object
 5   Product line             1014 non-null   object
 6   Unit price               990 non-null    float64
 7   Quantity                 1014 non-null   int64
 8   Tax 5%                   1014 non-null   float64
 9   Sales                    994 non-null    object
 10  Date                     1002 non-null   object
 11  Time                     1014 non-null   object
 12  Payment                  1014 non-null   object
 13     cogs                  1014 non-null   float64
 14  gross margin percentage  1014 non-null   float64
 15  gross income             1014 non-null   float64
 16  Rating                   1014 non-null   float64
dtypes: float64(6), int64(1), object(10)
memory usage: 134.8+ KB

In [386]:
print('Number of Null Values:')
df.isnull().sum()

Number of Null Values:

Invoice ID                  0
Branch                      0
City                        0
   Customer type            0
Gender                      0
Product line                0
Unit price                 24
Quantity                    0
Tax 5%                      0
Sales                      20
Date                       12
Time                        0
Payment                     0
   cogs                     0
gross margin percentage     0
gross income                0
Rating                      0
dtype: int64

In [387]:
print(f'Number of Duplicates: {df.duplicated().sum()}')

Number of Duplicates: 14

In [388]:
df.describe()

,Unit price,Quantity,Tax 5%,cogs,gross margin percentage,gross income,Rating
count,990.000000,1014.000000,1014.000000,1014.000000,1.014000e+03,1014.000000,1014.000000
mean,55.520333,5.502959,15.336872,306.737436,4.761905e+00,15.336872,6.960454
std,26.330508,2.927133,11.685945,233.718896,6.220317e-14,11.685945,1.721264
min,10.080000,1.000000,0.508500,10.170000,4.761905e+00,0.508500,4.000000
25%,33.202500,3.000000,5.864625,117.292500,4.761905e+00,5.864625,5.500000
50%,54.890000,5.000000,12.066000,241.320000,4.761905e+00,12.066000,6.900000
75%,77.667500,8.000000,22.428000,448.560000,4.761905e+00,22.428000,8.475000
max,99.960000,10.000000,49.650000,993.000000,4.761905e+00,49.650000,10.000000

In [389]:
df['Gender'].value_counts()

Gender
Female    566
Male      426
F          13
M           9
Name: count, dtype: int64

In [390]:
df['   Customer type'].value_counts()

   Customer type
Member    570
Normal    444
Name: count, dtype: int64

## *Data Cleaning*

In [391]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.22,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.048,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,NaN,10:37:00 AM,E-wallet,604.17,4.761905,30.2085,5.3

In [392]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1014 non-null   object
 1   Branch                   1014 non-null   object
 2   City                     1014 non-null   object
 3      Customer type         1014 non-null   object
 4   Gender                   1014 non-null   object
 5   Product line             1014 non-null   object
 6   Unit price               990 non-null    float64
 7   Quantity                 1014 non-null   int64
 8   Tax 5%                   1014 non-null   float64
 9   Sales                    994 non-null    object
 10  Date                     1002 non-null   object
 11  Time                     1014 non-null   object
 12  Payment                  1014 non-null   object
 13     cogs                  1014 non-null   float64
 14  gross margin percentage  1014 non-null   float64
 15  gross income             1014 non-null   float64
 16  Rating                   1014 non-null   float64
dtypes: float64(6), int64(1), object(10)
memory usage: 134.8+ KB

In [393]:
df.columns = df.columns.str.strip()

In [394]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1014 non-null   object
 1   Branch                   1014 non-null   object
 2   City                     1014 non-null   object
 3   Customer type            1014 non-null   object
 4   Gender                   1014 non-null   object
 5   Product line             1014 non-null   object
 6   Unit price               990 non-null    float64
 7   Quantity                 1014 non-null   int64
 8   Tax 5%                   1014 non-null   float64
 9   Sales                    994 non-null    object
 10  Date                     1002 non-null   object
 11  Time                     1014 non-null   object
 12  Payment                  1014 non-null   object
 13  cogs                     1014 non-null   float64
 14  gross margin percentage  1014 non-null   float64
 15  gross income             1014 non-null   float64
 16  Rating                   1014 non-null   float64
dtypes: float64(6), int64(1), object(10)
memory usage: 134.8+ KB

In [395]:
df['Branch'].unique()

array(['Alex', 'Giza', 'Cairo', '     Cairo', 'giza', 'cairo',
       '      Cairo       ', 'Alex     '], dtype=object)

In [396]:
df['Branch'] = df['Branch'].str.strip().replace({'giza':'Giza' , 'cairo':'Cairo'})

In [397]:
df['Branch'].unique()

array(['Alex', 'Giza', 'Cairo'], dtype=object)

In [398]:
df['City'].unique()

array(['Yangon', 'Naypyitaw', 'Mandalay'], dtype=object)

In [399]:
df['Customer type'].unique()

array(['Member', 'Normal'], dtype=object)

In [400]:
df['Gender'].unique()

array(['Female', 'F', 'Male', 'M'], dtype=object)

In [401]:
df['Gender'] = df['Gender'].replace({'F':'Female' , 'M':'Male'})

In [402]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [403]:
df['Product line'].unique()

array(['Health and beauty', 'Electronic accessories',
       'Home and lifestyle', 'Sports and travel', 'Food and beverages',
       'Fashion accessories'], dtype=object)

In [404]:
df['Unit price'].astype('float64')

0       74.69
1       15.28
2       46.33
3       58.22
4       86.31
        ...
1009    56.56
1010    76.60
1011    58.03
1012    17.49
1013    60.95
Name: Unit price, Length: 1014, dtype: float64

In [405]:
df['Unit price'] = df['cogs']/df['Quantity']

In [406]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1014 non-null   object
 1   Branch                   1014 non-null   object
 2   City                     1014 non-null   object
 3   Customer type            1014 non-null   object
 4   Gender                   1014 non-null   object
 5   Product line             1014 non-null   object
 6   Unit price               1014 non-null   float64
 7   Quantity                 1014 non-null   int64
 8   Tax 5%                   1014 non-null   float64
 9   Sales                    994 non-null    object
 10  Date                     1002 non-null   object
 11  Time                     1014 non-null   object
 12  Payment                  1014 non-null   object
 13  cogs                     1014 non-null   float64
 14  gross margin percentage  1014 non-null   float64
 15  gross income             1014 non-null   float64
 16  Rating                   1014 non-null   float64
dtypes: float64(6), int64(1), object(10)
memory usage: 134.8+ KB

In [407]:
df['Sales'] = df['Quantity'] * df['Unit price'] + df['Tax 5%']

In [408]:
df['Sales'].astype("float64")

0       548.9715
1        80.2200
2       340.5255
3       489.0480
4       634.3785
          ...
1009    296.9400
1010    804.3000
1011    121.8630
1012    183.6450
1013     63.9975
Name: Sales, Length: 1014, dtype: float64

In [409]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1014 non-null   object
 1   Branch                   1014 non-null   object
 2   City                     1014 non-null   object
 3   Customer type            1014 non-null   object
 4   Gender                   1014 non-null   object
 5   Product line             1014 non-null   object
 6   Unit price               1014 non-null   float64
 7   Quantity                 1014 non-null   int64
 8   Tax 5%                   1014 non-null   float64
 9   Sales                    1014 non-null   float64
 10  Date                     1002 non-null   object
 11  Time                     1014 non-null   object
 12  Payment                  1014 non-null   object
 13  cogs                     1014 non-null   float64
 14  gross margin percentage  1014 non-null   float64
 15  gross income             1014 non-null   float64
 16  Rating                   1014 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 134.8+ KB

In [410]:
df.dropna(inplace=True)

In [411]:
df['Date'] = pd.to_datetime(df['Date'])

In [412]:
df["Day"] = df['Date'].dt.day_name()
df["Month"] = df['Date'].dt.month_name()
df["Year"] = df['Date'].dt.year

In [413]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Day,Month,Year
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1,Saturday,January,2019
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6,Friday,March,2019
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4,Sunday,March,2019
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4,Sunday,January,2019
16,656-95-9349,Alex,Yangon,Member,Female,Health and beauty,68.93,7,24.1255,506.6355,2019-03-11,11:03:00 AM,Credit card,482.51,4.761905,24.1255,4.6,Monday,March,2019

In [414]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1002 entries, 0 to 1013
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1002 non-null   object
 1   Branch                   1002 non-null   object
 2   City                     1002 non-null   object
 3   Customer type            1002 non-null   object
 4   Gender                   1002 non-null   object
 5   Product line             1002 non-null   object
 6   Unit price               1002 non-null   float64
 7   Quantity                 1002 non-null   int64
 8   Tax 5%                   1002 non-null   float64
 9   Sales                    1002 non-null   float64
 10  Date                     1002 non-null   datetime64[ns]
 11  Time                     1002 non-null   object
 12  Payment                  1002 non-null   object
 13  cogs                     1002 non-null   float64
 14  gross margin percentage  1002 non-null   float64
 15  gross income             1002 non-null   float64
 16  Rating                   1002 non-null   float64
 17  Day                      1002 non-null   object
 18  Month                    1002 non-null   object
 19  Year                     1002 non-null   int32
dtypes: datetime64[ns](1), float64(7), int32(1), int64(1), object(10)
memory usage: 192.8+ KB

In [415]:
df['Time'] = pd.to_datetime(df['Time']).dt.strftime('%H:%M:%S')

/tmp/ipykernel_805/79893418.py:1: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

In [416]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Day,Month,Year
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08:00,Ewallet,522.83,4.761905,26.1415,9.1,Saturday,January,2019
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00,Cash,76.40,4.761905,3.8200,9.6,Friday,March,2019
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23:00,Credit card,324.31,4.761905,16.2155,7.4,Sunday,March,2019
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33:00,Ewallet,465.76,4.761905,23.2880,8.4,Sunday,January,2019
16,656-95-9349,Alex,Yangon,Member,Female,Health and beauty,68.93,7,24.1255,506.6355,2019-03-11,11:03:00,Credit card,482.51,4.761905,24.1255,4.6,Monday,March,2019

In [417]:
df['Payment'].unique()

array(['Ewallet', 'Cash', 'Credit card', 'credit card', 'cash'],
      dtype=object)

In [418]:
df['Payment'] = df['Payment'].replace({
    'Ewallet':'E-Wallet',
    'cash':'Cash',
    'credit card':'Credit card'
})

In [419]:
df['Payment'].unique()

array(['E-Wallet', 'Cash', 'Credit card'], dtype=object)

In [420]:
# Cogs = Quantity * Unit Price so i will change name to "Total Price" , Sales to Tatal Salary   ,    Tax 5% to Tax(TS - TP)
df.rename(columns={'cogs':'Total Price' , 'Sales':'Total Salary' , 'Tax 5%':'Tax(TS - TP)'}, inplace=True)

In [421]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax(TS - TP),Total Salary,Date,Time,Payment,Total Price,gross margin percentage,gross income,Rating,Day,Month,Year
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08:00,E-Wallet,522.83,4.761905,26.1415,9.1,Saturday,January,2019
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00,Cash,76.40,4.761905,3.8200,9.6,Friday,March,2019
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23:00,Credit card,324.31,4.761905,16.2155,7.4,Sunday,March,2019
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33:00,E-Wallet,465.76,4.761905,23.2880,8.4,Sunday,January,2019
16,656-95-9349,Alex,Yangon,Member,Female,Health and beauty,68.93,7,24.1255,506.6355,2019-03-11,11:03:00,Credit card,482.51,4.761905,24.1255,4.6,Monday,March,2019

In [422]:
# gross margin percentage is the same number , we can drop column
# gross income = Tax 5% ,drop
# drop Invoice id because we don't benefit from it
# drop City because Branch is enough
df.drop(columns=['gross margin percentage', 'gross income', 'Invoice ID' , 'City'], inplace=True)

In [423]:
df.head()

,Branch,Customer type,Gender,Product line,Unit price,Quantity,Tax(TS - TP),Total Salary,Date,Time,Payment,Total Price,Rating,Day,Month,Year
0,Alex,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08:00,E-Wallet,522.83,9.1,Saturday,January,2019
1,Giza,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00,Cash,76.40,9.6,Friday,March,2019
2,Alex,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23:00,Credit card,324.31,7.4,Sunday,March,2019
3,Alex,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33:00,E-Wallet,465.76,8.4,Sunday,January,2019
16,Alex,Member,Female,Health and beauty,68.93,7,24.1255,506.6355,2019-03-11,11:03:00,Credit card,482.51,4.6,Monday,March,2019

In [424]:
def satisfaction(rating):
  if rating >= 7:
    return "Satisfied"
  else:
    return "Not Satisfied"

In [425]:
df["Satisfaction"] = df["Rating"].apply(satisfaction)

In [426]:
df.sort_values(by='Total Salary', ascending=False, inplace=True)

In [427]:
df.head()

,Branch,Customer type,Gender,Product line,Unit price,Quantity,Tax(TS - TP),Total Salary,Date,Time,Payment,Total Price,Rating,Day,Month,Year,Satisfaction
350,Giza,Member,Female,Fashion accessories,99.30,10,49.65,1042.65,2019-02-15,14:53:00,Credit card,993.0,6.6,Friday,February,2019,Not Satisfied
167,Alex,Normal,Male,Fashion accessories,98.98,10,49.49,1039.29,2019-02-08,16:20:00,Credit card,989.8,8.7,Friday,February,2019,Satisfied
557,Giza,Member,Female,Food and beverages,98.52,10,49.26,1034.46,2019-01-30,20:23:00,E-Wallet,985.2,4.5,Wednesday,January,2019,Not Satisfied
699,Giza,Normal,Male,Home and lifestyle,97.50,10,48.75,1023.75,2019-01-12,16:18:00,E-Wallet,975.0,8.0,Saturday,January,2019,Satisfied
996,Cairo,Normal,Female,Home and lifestyle,97.38,10,48.69,1022.49,2019-03-02,17:16:00,E-Wallet,973.8,4.4,Saturday,March,2019,Not Satisfied

In [428]:
df.drop_duplicates(inplace=True)

In [429]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 988 entries, 350 to 822
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Branch         988 non-null    object
 1   Customer type  988 non-null    object
 2   Gender         988 non-null    object
 3   Product line   988 non-null    object
 4   Unit price     988 non-null    float64
 5   Quantity       988 non-null    int64
 6   Tax(TS - TP)   988 non-null    float64
 7   Total Salary   988 non-null    float64
 8   Date           988 non-null    datetime64[ns]
 9   Time           988 non-null    object
 10  Payment        988 non-null    object
 11  Total Price    988 non-null    float64
 12  Rating         988 non-null    float64
 13  Day            988 non-null    object
 14  Month          988 non-null    object
 15  Year           988 non-null    int32
 16  Satisfaction   988 non-null    object
dtypes: datetime64[ns](1), float64(5), int32(1), int64(1), object(9)
memory usage: 135.1+ KB

In [430]:
df.to_csv('Cleaned_SuperMarket.csv', index=False)

## *Data Analysis*

In [431]:
df = pd.read_csv("/content/Cleaned_SuperMarket.csv")

In [432]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Branch         988 non-null    object
 1   Customer type  988 non-null    object
 2   Gender         988 non-null    object
 3   Product line   988 non-null    object
 4   Unit price     988 non-null    float64
 5   Quantity       988 non-null    int64
 6   Tax(TS - TP)   988 non-null    float64
 7   Total Salary   988 non-null    float64
 8   Date           988 non-null    object
 9   Time           988 non-null    object
 10  Payment        988 non-null    object
 11  Total Price    988 non-null    float64
 12  Rating         988 non-null    float64
 13  Day            988 non-null    object
 14  Month          988 non-null    object
 15  Year           988 non-null    int64
 16  Satisfaction   988 non-null    object
dtypes: float64(5), int64(2), object(10)
memory usage: 131.3+ KB

In [433]:
profile = ProfileReport(df)

In [434]:
profile.to_file("Report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/17 [00:00<?, ?it/s]
 24%|██▎       | 4/17 [00:00<00:00, 38.54it/s]
 53%|█████▎    | 9/17 [00:00<00:00, 33.26it/s]
100%|██████████| 17/17 [00:00<00:00, 41.03it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [435]:
# 1)Provide the total revenue generated by the supermarket.
print(f'Total Reveue: {df['Total Salary'].sum().round(1)} $')

Total Reveue: 318041.9 $

In [436]:
# 2) Provide the total revenue by city and identify the city with the highest revenue.
df.groupby('Branch')['Total Salary'].sum().sort_values(ascending=False).round(1)

Branch
Giza     109168.7
Cairo    105266.5
Alex     103606.7
Name: Total Salary, dtype: float64

In [437]:
print(f"The City that have the Highest Revenue: {df.groupby('Branch')['Total Salary'].sum().idxmax()}")

The City that have the Highest Revenue: Giza

In [438]:
# 3) Provide the total profit by branch and identify the most profitable branch.
df.groupby('Branch')['Total Price'].sum().sort_values(ascending=False).round(1)

Branch
Giza     103970.2
Cairo    100253.8
Alex      98673.0
Name: Total Price, dtype: float64

In [439]:
print(f"The City that have the Highest Profit: {df.groupby('Branch')['Total Price'].sum().idxmax()}")

The City that have the Highest Profit: Giza

In [440]:
# 4) Provide the total revenue and profit by product category and identify the top-performing category.
df.groupby('Product line')[['Total Salary', 'Total Price']].sum().sort_values(by='Total Salary', ascending=False).round(1)

                        Total Salary  Total Price
Product line
Food and beverages           55518.6      52874.9
Fashion accessories          54245.1      51662.0
Sports and travel            53898.0      51331.4
Home and lifestyle           53089.5      50561.5
Electronic accessories       52922.6      50402.5
Health and beauty            48368.1      46064.9

In [441]:
print(f"The Product Category that have the Highest Revenue: {df.groupby('Product line')['Total Salary'].sum().idxmax()}")

The Product Category that have the Highest Revenue: Food and beverages

In [442]:
fig1 = px.bar(df, x='Product line', y='Total Salary', color='Branch', title='Total Revenue by Product Category')
fig1.show()

In [443]:
# 5) Provide the total spending by customer type and identify which customer type spends more.
df.groupby('Customer type')['Total Salary'].sum().sort_values(ascending=False).round(1)

Customer type
Member    184769.9
Normal    133272.0
Name: Total Salary, dtype: float64

In [444]:
print(f"The Customer Type that have the Highest Spending: {df.groupby('Customer type')['Total Salary'].sum().idxmax()}")

The Customer Type that have the Highest Spending: Member

In [445]:
# 6) Provide the number of transactions by payment method and identify the most popular payment method.
df['Payment'].value_counts()

Payment
Cash           341
E-Wallet       338
Credit card    309
Name: count, dtype: int64

In [446]:
print(f"The Payment Method that have the Highest Transactions: {df['Payment'].value_counts().idxmax()}")

The Payment Method that have the Highest Transactions: Cash

In [447]:
fig2 = px.pie(df, names='Payment', title='Number of Transactions by Payment Method')
fig2.show()

In [448]:
# 7) Provide the average transaction value for the supermarket.
print(f'The Average Transaction Value: {df["Total Salary"].mean().round(1)} $')

The Average Transaction Value: 321.9 $

In [449]:
# 8) Provide the customer satisfaction percentage by branch and identify the branch with the highest satisfaction.
df.groupby('Branch')['Satisfaction'].value_counts(normalize=True).mul(100).round(1).unstack()

Satisfaction  Not Satisfied  Satisfied
Branch
Alex                   47.3       52.7
Cairo                  54.0       46.0
Giza                   47.9       52.1

In [450]:
print(f"The Branch that have the Highest Satisfaction: {df.groupby('Branch')['Satisfaction'].value_counts(normalize=True).mul(100).idxmax()}")

The Branch that have the Highest Satisfaction: ('Cairo', 'Not Satisfied')

In [451]:
# 9) Provide the total revenue by day and by month and identify the day and month with the highest sales.
df.groupby('Day')['Total Salary'].sum().sort_values(ascending=False).round(1)

Day
Saturday     56013.7
Tuesday      50645.3
Thursday     44819.6
Sunday       43685.5
Wednesday    43497.6
Friday       42542.5
Monday       36837.8
Name: Total Salary, dtype: float64

In [452]:
df.groupby('Month')['Total Salary'].sum().sort_values(ascending=False).round(1)

Month
January     115625.3
March       107971.3
February     94445.4
Name: Total Salary, dtype: float64

In [453]:
df.groupby(['Day', 'Month'])['Total Salary'].sum().sort_values(ascending=False).round(1).unstack()

Month      February  January    March
Day
Friday      16167.9  11219.5  15155.1
Monday      12851.2  14192.7   9793.9
Saturday    12256.2  18093.7  25663.8
Sunday      15858.6  14356.8  13470.2
Thursday    12719.6  19340.2  12759.8
Tuesday     12419.9  20614.1  17611.3
Wednesday   12172.0  17808.4  13517.2

In [454]:
fig3 = px.bar(df, x='Day', y='Total Salary', color='Month', title='Total Revenue by Day and Month')
fig3.show()

In [455]:
print(f"The Day that have the Highest Sales: {df.groupby('Day')['Total Salary'].sum().idxmax()}")
print(f"The Month that have the Highest Sales: {df.groupby('Month')['Total Salary'].sum().idxmax()}")

The Day that have the Highest Sales: Saturday
The Month that have the Highest Sales: January

In [456]:
# 10) Provide the overall percentage of satisfied customers/transactions.
df['Satisfaction'].value_counts(normalize=True).mul(100).round(1)

Satisfaction
Satisfied        50.3
Not Satisfied    49.7
Name: proportion, dtype: float64

In [457]:
fig4 = px.pie(df, names='Satisfaction', title='Overall Percentage of Satisfied Customers/Transactions')
fig4.show()